[project]
name = "python-sandbox"
version = "0.1.0"
description = "Python sandbox to learn and play"
readme = "README.md"
authors = [
    { name = "Di P", email = "popov.dmitriiy@gmail.com" }
]
requires-python = "==3.14.*"

[tool.mypy]
python_version = "3.14"
warn_unused_ignores = true
warn_reduncant_casts = true
disallow_incomplete_defs = true
no_implicit_optional = true
exclude = [
    "^tests/",
    "^alembic/versions/"
]

[tool.uv.workspace]
members = ["packages/*"]

[tool.pytest.ini_options]
testpaths = [
    "apps/release_tracker/tests",
    "apps/sandbox/tests",
]

[dependency-groups]
dev = [
    "basedpyright",
    "coverage>=7.16.0",
    "mypy>=2.3.1",
    "prek>=0.5.2",
    "pytest>=9.1.1",
    "ruff>=0.16.6",
]
