[project]
name = "release-tracker"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Di P", email = "popov.dmitriiy@gmail.com" }
]
requires-python = "==3.14.*"
dependencies = [
    "alembic>=1.19.2",
    "fastapi[standard]>=0.115.0",
    "psycopg[binary]>=3.3.5",
    "pwdlib[argon2]>=0.3.1",
    "pydantic-settings>=2.15.0",
    "pyjwt>=2.13.0",
    "sqlalchemy>=2.0.52",
    "sqlmodel>=0.0.42",
]

[tool.fastapi]
entrypoint = "release_tracker.main:app"

[tool.mypy]
python_version = "3.14"
warn_unused_ignores = true
warn_reduncant_casts = true
disallow_incomplete_defs = true
no_implicit_optional = true
exclude = [
    "^tests/",
    "^alembic/versions/"
]

[build-system]
requires = ["uv_build>=0.12.9,<0.13.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "coverage>=7.16.0",
    "mypy>=2.3.1",
    "prek>=0.5.2",
    "pytest>=9.1.1",
    "ruff>=0.16.6",
]
