services:
  db:
    image: pgvector/pgvector:pg18-trixie
    ports:
      - "5430:5432"
    environment:
      POSTGRES_DB: sandbox
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d sandbox"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - postgres_data:/var/lib/postresql/data

  ollama:
    image: ollama/ollama:latest
    ports:
      - "11434:11434"
    healthcheck:
      test: ["CMD", "ollama", "list"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - ollama:/root/.ollama

  ollama-pull:
    image: ollama/ollama:latest
    depends_on:
      ollama:
        condition: service_healthy
    environment:
      OLLAMA_HOST: http://ollama:11434
    entrypoint: ["ollama", "pull", "nomic-embed-text"]
    restart: "no"
    volumes:
      - ollama:/root/.ollama

volumes:
  postgres_data:
  ollama:
